version: 2
jobs:
  build:
    working_directory: ~/Streampunk/beamengine
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      UV_THREADPOOL_SIZE: 16
    docker:
    - image: streampunkmedia/testbeam:10-4.1
    - image: circleci/redis
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: npm install tap-xunit
    - run: npm install --unsafe-perm
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules
    - run: echo 'export PATH="~/Streampunk/beamengine/node_modules/.bin:$PATH"' >> $BASH_ENV
    - run: mkdir -p $CIRCLE_TEST_REPORTS/eslint
    - run: mkdir -p $CIRCLE_TEST_REPORTS/xunit
    - run: eslint '**/*.js' -f junit -o /tmp/circleci-test-results/eslint/eslint.xml
    - run:
        name: Install dockerize
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.6.1
    - run:
        name: Wait for redis
        command: dockerize -wait tcp://localhost:6379 -timeout 1m
    - run:
        name: Run tests
        command: set -eo pipefail && npm test | tap-xunit > /tmp/circleci-test-results/xunit/results.xml
      
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
